baseURL = "https://yueye231300.github.io/my-blog/"
title = "æˆ‘çš„åšå®¢"
pagerSize = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "æˆ‘çš„åšå®¢"
  description = "æ¬¢è¿è®¿é—®æˆ‘çš„åšå®¢"
  author = "yueye231300"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  math = true

[params.homeInfoParams]
  Title = "ğŸ‘‹ æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢"
  Content = """
è¿™é‡Œä¸»è¦ç”¨æ¥å­˜å‚¨æˆ‘çš„ä½œä¸šå’Œä¸€äº›æŠ€æœ¯é—®é¢˜
- åœ¨è¿™é‡Œæˆ‘å°†åˆ†äº«æˆ‘çš„æƒ³æ³•å’Œç»éªŒã€‚
"""

[[menu.main]]
  identifier = "categories"
  name = "åˆ†ç±»"
  url = "/categories/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "æ ‡ç­¾"
  url = "/tags/"
  weight = 20
  
[[menu.main]]
  identifier = "archives"
  name = "å½’æ¡£"
  url = "/archives/"
  weight = 30

[[menu.main]]
  identifier = "homework"
  name = "è¯¾ç¨‹ä½œä¸š"
  url = "posts/homework/"
  weight = 40